services:
  qdrant:
    image: 'qdrant/qdrant:v1.13.0'
    ports:
      - "6333:6333"
      - "6334:6334"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus.yml
    networks:
      - spring-ai
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - spring-ai

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI port
      - "4317:4317"   # gRPC port
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - spring-ai

volumes:
  grafana_storage:

networks:
  spring-ai:
    driver: bridge